# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitialPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shuffled_position', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
            options={
                'ordering': ('game', 'shuffled_position'),
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('move_number', models.IntegerField()),
                ('bottom_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_bottom_card', to='api.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('top_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_top_card', to='api.Card')),
            ],
            options={
                'ordering': ('game', 'move_number'),
            },
        ),
    ]
